version: '2.4'
services:
  postgres:
    container_name: mattermost-postgres
    ports:
      - "5432:5432"
    extends:
        file: docker-compose.common.yml
        service: postgres
    tmpfs: /var/lib/postgresql/data
  minio:
    container_name: mattermost-minio
    ports:
      - "9000:9000"
    extends:
        file: docker-compose.common.yml
        service: minio
  inbucket:
    container_name: mattermost-inbucket
    ports:
      - "10025:10025"
      - "10080:10080"
      - "10110:10110"
    extends:
        file: docker-compose.common.yml
        service: inbucket
  openldap:
    container_name: mattermost-openldap
    ports:
      - "389:389"
      - "636:636"
    extends:
        file: docker-compose.common.yml
        service: openldap
  elasticsearch:
    container_name: mattermost-elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    extends:
        file: docker-compose.common.yml
        service: elasticsearch
  keycloak:
    container_name: mattermost-saml
    ports:
      - "8484:8080"
    extends:
        file: docker-compose.common.yml
        service: keycloak

  start_dependencies:
    image: mattermost/mattermost-wait-for-dep:latest
    networks:
      - mm-test
    depends_on:
      - postgres
      - minio
      - inbucket
      - openldap
      - elasticsearch
      - keycloak
    command: postgres:5432 minio:9000 inbucket:10080 openldap:389 elasticsearch:9200

networks:
  mm-test:
    driver: bridge
